# Generated by Django 4.2.1 on 2023-07-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.PROTECT, to='news.author', verbose_name='Автор'),
        ),
    ]
